using System;
using System.Collections.Generic;
using System.Linq;
using System.Text;
using System.Threading.Tasks;

namespace EasyCheats
{
    class Data
    {
        static public string[] allUnitsInOneArray = new String[] {
            "00",
            "Vishnu",
            "Mithra",
            "Amaterasu",
            "Odin",
            "Atavaka",
            "Horus",
            "Laksmi",
            "Scathach",
            "Sarasvati",
            "Sati",
            "Uzume",
            "Shiva",
            "Beiji-Weng",
            "Wu Kong",
            "Dionysus",
            "Kali",
            "Skadi",
            "Parvati",
            "Kushinada",
            "Kikuri-Hime",
            "Bishamon",
            "Thor",
            "Jikoku",
            "Mikazuchi",
            "Okuninushi",
            "Koumoku",
            "Zouchou",
            "Minakata",
            "Chimera",
            "Baihu",
            "Senri",
            "Feng Huang",
            "Shiisaa",
            "Cai-Zhi",
            "Unicorn",
            "Flaemis",
            "Aquans",
            "Aeros",
            "Erthys",
            "Saki Mitama",
            "Kusi Mitama",
            "Nigi Mitama",
            "Ara Mitama",
            "Efreet",
            "Purski",
            "Onkot",
            "Jinn",
            "Karasu",
            "Dis",
            "Isora",
            "Apsaras",
            "Koppa",
            "Titania",
            "Oberon",
            "Troll",
            "Setanta",
            "Kelpie",
            "Pyro Jack",
            "High Pixie",
            "Jack Frost",
            "Pixie",
            "Throne",
            "Dominion",
            "Virtue",
            "Power",
            "Principality",
            "Archangel",
            "Angel",
            "Flauros",
            "Decarabia",
            "Ose",
            "Berith",
            "Eligor",
            "Forneus",
            "Yurlungur",
            "Quetzalcoatl",
            "Raja Naga",
            "Mizuchi",
            "Naga",
            "Nozuchi",
            "Cerberus",
            "Orthrus",
            "Sparna",
            "Badb Catha",
            "Inugami",
            "Nekomata",
            "Gogmagog",
            "Titan",
            "Sarutahiko",
            "Sudama",
            "Hua Po",
            "Kodama",
            "Shiki-Ouji",
            "Oni",
            "Ikusa",
            "Momunofu",
            "Shikigami",
            "Rangda",
            "Dakini",
            "Yaksini",
            "Shikome",
            "Taraka",
            "Datsue-Ba",
            "Mada",
            "Girimehkala",
            "Tao Tie",
            "Pazuzu",
            "Baphomet",
            "Mot",
            "Aciel",
            "Surt",
            "Abaddon",
            "Loki",
            "Lilith",
            "Nyx",
            "Queen Mab",
            "Succubus",
            "Incubus",
            "Fomor",
            "Lilim",
            "Hresvelgr",
            "Mothman",
            "Raiju",
            "Nue",
            "Bicorn",
            "Zhen",
            "Rakshasa",
            "Legion",
            "Yaka",
            "Choronzon",
            "Preta",
            "Shadow",
            "Black Ooze",
            "Blob",
            "Slime",
            "Mou-Ryo",
            "Will o' Wisp",
            "Michael",
            "Gabriel",
            "Raphael",
            "Uriel",
            "Ganesha",
            "Valkyrie",
            "Arahabaki",
            "Kurama",
            "Hanuman",
            "Cu Chulainn",
            "Long",
            "Gui Xian",
            "Barong",
            "Makami",
            "Garuda",
            "Yatagarasu",
            "Gurr",
            "Albion",
            "Manikin",
            "Manikin",
            "Manikin",
            "Manikin",
            "Manikin",
            "Samael",
            "Manikin",
            "Manikin",
            "Manikin",
            "Manikin",
            "Manikin",
            "Pisaca",
            "Kaiwan",
            "Kin-Ki",
            "Sui-Ki",
            "Fuu-Ki",
            "Ongyo-Ki",
            "Clotho",
            "Lachesis",
            "Atropos",
            "Loa",
            "Chatterskull",
            "Phantom",
            "0xB3",
            "0xB4",
            "0xB5",
            "0xB6",
            "0xB7",
            "0xB8",
            "0xB9",
            "0xBA",
            "0xBB",
            "0xBC",
            "0xBD",
            "0xBE",
            "0xBF",
            "Dante/Raidou",
            "Metatron",
            "Beelzebub",
            "Pale Rider",
            "White Rider",
            "Red Rider",
            "Black Rider",
            "Matador",
            "Hell Biker",
            "Daisoujou",
            "The Harlot",
            "Trumpeter",
            "Futomimi",
            "Sakahagi",
            "Black Frost",
            "Beelzebub",
            "0xD0",
            "0xD1",
            "0xD2",
            "0xD3",
            "0xD4",
            "0xD5",
            "0xD6",
            "0xD7",
            "0xD8",
            "0xD9",
            "0xDA",
            "0xDB",
            "0xDC",
            "0xDD",
            "0xDE",
            "0xDF",
            "0xE0",
            "0xE1",
            "0xE2",
            "0xE3",
            "0xE4",
            "0xE5",
            "0xE6",
            "0xE7",
            "0xE8",
            "0xE9",
            "0xEA",
            "0xEB",
            "0xEC",
            "0xED",
            "0xEE",
            "0xEF",
            "0xF0",
            "0xF1",
            "0xF2",
            "0xF3",
            "0xF4",
            "0xF5",
            "0xF6",
            "0xF7",
            "0xF8",
            "0xF9",
            "0xFA",
            "0xFB",
            "0xFC",
            "0xFD",
            "0xFE",
            "Protegonist",
            "Forneus",
            "Specter",
            "Ahriman",
            "Noah",
            "Incubus",
            "Koppa",
            "Kaiwan",
            "Ose",
            "Kagutsuchi",
            "Mizuchi",
            "Kin-Ki",
            "Sui-Ki",
            "Fuu-Ki",
            "Ongyo-Ki",
            "Clotho",
            "Lachesis",
            "Atropos",
            "Specter",
            "Girimehkala",
            "Specter",
            "Aciel",
            "Skadi",
            "Albion",
            "Urthona",
            "Urizen",
            "Luvah",
            "Tharmus",
            "Futomimi",
            "Gabriel",
            "Raphael",
            "Uriel",
            "Samael",
            "Baal Avatar",
            "Ose Hallel",
            "Flauros Hallel",
            "Ahriman",
            "Noah",
            "Kagutsuchi",
            "Specter",
            "Specter",
            "Specter",
            "Mizuchi",
            "Reserve",
            "Sakahagi",
            "Orthrus",
            "Yaksini",
            "Thor",
            "Black Frost",
            "Karasu",
            "Karasu",
            "Karasu",
            "Eligor",
            "Eligor",
            "Eligor",
            "Kelpie",
            "Kelpie",
            "Berith",
            "Succubus",
            "High Pixie",
            "Kaiwan",
            "Nekomata",
            "Troll",
            "Will o' Wisp",
            "Preta",
            "Bishamon",
            "Mara",
            "Bishamon",
            "Jikoku",
            "Koumoku",
            "Zouchou",
            "Clotho",
            "Lachesis",
            "Atropos",
            "Mithra",
            "Masakado",
            "Station Hand",
            "Loki",
            "Mada",
            "Mot",
            "Surt",
            "Pyro Jack",
            "Thor",
            "Shade",
            "Dante/Raidou",
            "Dante/Raidou",
            "Dante/Raidou",
            "Metatron",
            "Beelzebub",
            "Lucifer",
            "Pale Rider",
            "White Rider",
            "Red Rider",
            "Black Rider",
            "Matador",
            "Hell Biker",
            "Daisoujou",
            "The Harlot",
            "Trumpeter",
            "Futomimi",
            "Sakahagi",
            "Seven-Eye",
            "BeelzebubM",
            "Loa",
            "Virtue",
            "Power",
            "Legion",
            "Reserve",
            "Reserve",
            "Reserve",
            "Reserve",
            "Reserve",
            "Reserve",
            "Reserve",
            "Reserve",
            "Reserve",
            "Reserve",
            "Reserve",
            "Reserve",
            "Reserve",
            "Reserve",
            "Reserve",
            "Reserve",
            "Reserve",
            "Reserve",
            "Reserve",
            "Reserve",
            "Reserve",
            "Reserve",
            "Reserve"
        };
    
        static public string[] allItemsInOneArray = new String[] {
            "Reserve",
            "Muscle Drink",
            "Medicine",
            "Life Stone",
            "Bead",
            "Bead Chain",
            "Chakra Drop",
            "Chakra Pot",
            "Great Chakra",
            "Soma Droplet",
            "Soma",
            "Bead of Life",
            "Chakra Elixir",
            "Revival Bead",
            "Balm of Rising",
            "Sacred Water",
            "Dis-Poison",
            "Dis-Stun",
            "Dis-Charm",
            "Dis-Mute",
            "Dis-Stone",
            "Maragi Rock",
            "Mabufu Rock",
            "Mazio Rock",
            "Mazan Rock",
            "Mahama Rock",
            "Mamudo Rock",
            "Megido Rock",
            "Megidola Rock",
            "Poison Arrow",
            "Wagtail Plume",
            "Makajam Rock",
            "Pot of Death",
            "Reserve",
            "Magic Mirror",
            "Attack Mirror",
            "Dekaja Rock",
            "Tetraja Rock",
            "St Incense",
            "Reserve",
            "Ma Incense",
            "Vi Incense",
            "Ag Incense",
            "Lu Incense",
            "Blessed Fan",
            "Soul-Return",
            "Spyglass",
            "Reserve",
            "Reserve",
            "Reserve",
            "Reserve",
            "Reserve",
            "Repulse Bell",
            "Attract Pipe",
            "Float Ball",
            "Light Ball",
            "Smoke Ball",
            "Reserve",
            "Divining Water",
            "Reserve",
            "Reserve",
            "Lucky Ticket",
            "Reserve",
            "Reserve",
            "Marogareh",
            "Wadatsumi",
            "Ankh",
            "Iyomante",
            "Shiranui",
            "Hifumi",
            "Kamudo",
            "Narukami",
            "Anathema",
            "Miasma",
            "Nirvana",
            "Murakumo",
            "Geis",
            "Djed",
            "Muspell",
            "Gehenna",
            "Kamurogi",
            "Satan",
            "Adama",
            "Vimana",
            "Gundari",
            "Sophia",
            "Gaea",
            "Kailash",
            "Masakados",
            "Reserve",
            "Reserve",
            "Reserve",
            "Reserve",
            "Reserve",
            "Reserve",
            "Reserve",
            "Diamond",
            "Pearl",
            "Sapphire",
            "Emerald",
            "Ruby",
            "Jade",
            "Opal",
            "Amethyst",
            "Agate",
            "Turquoise",
            "Garnet",
            "Reserve",
            "Onyx",
            "Reserve",
            "Coral",
            "Aquamarine",
            "ID Card",
            "Annex Pass",
            "White Kila",
            "Yellow Kila",
            "Green Kila",
            "Red Kila",
            "1000 Yen Bill",
            "Letter",
            "Umugi Stone",
            "Spoon",
            "Himorogi",
            "Kimon Stone",
            "Lord's Sword",
            "Park Key",
            "Heavenstone",
            "Earthstone",
            "Netherstone",
            "Majesty",
            "Wisdom",
            "Insight",
            "Compassion",
            "Godliness",
            "Beauty",
            "Eternety",
            "Dignity",
            "Foundation",
            "Sovereignty",
            "Knowlegde",
            "Moon Key",
            "Deathstone",
            "Black Visor",
            "Afterlife Bell",
            "Star Key",
            "Reserve",
            "Reserve",
            "Reserve",
            "Reserve",
            "Reserve",
            "Reserve",
            "Reserve",
            "Reserve",
            "Reserve",
            "Reserve",
            "Reserve",
            "Reserve",
            "Reserve",
            "Reserve",
            "Reserve"
        };
    
        static public string[] allSkillsInOneArray = new String[] {
            "Blank",
            "Agi",
            "Agilao",
            "Agidyne",
            "Maragi",
            "Maragion",
            "Maragidyne",
            "Bufu",
            "Bufula",
            "Bufudyne",
            "Mabufu",
            "Mabufula",
            "Mabufudyne",
            "Zio",
            "Zionga",
            "Ziodyne",
            "Mazio",
            "Mazionga",
            "Maziodyne",
            "Zan",
            "Zanma",
            "Zandyne",
            "Mazan",
            "Mazanma",
            "Mazandyne",
            "Megido",
            "Megidola",
            "Megidolaon",
            "Hama",
            "Hamaon",
            "Mahama",
            "Mahamaon",
            "Mudo",
            "Mudoon",
            "Mamudo",
            "Mamudoon",
            "Dia",
            "Diarama",
            "Diarahan",
            "Media",
            "Mediarama",
            "Mediarahan",
            "Makatora",
            "Patra",
            "Me Patra",
            "Mutudi",
            "Posumudi",
            "Paraladi",
            "Petradi",
            "Recarm",
            "Samrecarm",
            "Recarmdra",
            "Tarunda",
            "Sukunda",
            "Rakunda",
            "Makajam",
            "Makajamon",
            "Dekaja",
            "Reserve",
            "Shibaboo",
            "Dormina",
            "Pulinpa",
            "Marin Karin",
            "Tentarafoo",
            "Tarukaja",
            "Sukukaja",
            "Rakukaja",
            "Makakaja",
            "Tetraja",
            "Makarakarn",
            "Tetrakarn",
            "Analyze",
            "Trafuri",
            "Estoma",
            "Riberama",
            "Liftoma",
            "Lightoma",
            "Dekunda",
            "0x04E",
            "Pestilence",
            "0x050",
            "0x051",
            "0x052",
            "0x053",
            "0x054",
            "0x055",
            "0x056",
            "0x057",
            "0x058",
            "0x059",
            "0x05A",
            "0x05B",
            "0x05C",
            "0x05D",
            "0x05E",
            "0x05F",
            "Lunge",
            "Hell Thrust",
            "Berserk",
            "Tempest",
            "Hades Blast",
            "Heat Wave",
            "Blight",
            "Brutal Slash",
            "Hassohappa",
            "Dark Sword",
            "Stasis Blade",
            "Mighty Gust",
            "Deathbound",
            "Guillotine",
            "Chaos Blade",
            "Needle Rush",
            "Stun Needle",
            "Toxic Sting",
            "Arid Needle",
            "Sacrifice",
            "Kamikaze",
            "Feral Bite",
            "Venom Bite",
            "Charme Bite",
            "Stone Bite",
            "Stun Bite",
            "Hell Fang",
            "Feral Claw",
            "Venom Claw",
            "Stun Claw",
            "Iron Claw",
            "Godly Light",
            "Reserve",
            "Reserve",
            "Reserve",
            "Deadly Fury",
            "Reserve",
            "Xeros-Beat",
            "Reserve",
            "Reserve",
            "Divine Shot",
            "Attack",
            "Attack",
            "Attack",
            "Attack",
            "Reserve",
            "Reserve",
            "Javelin Rain",
            "Oni-Kagura",
            "Reserve",
            "Reserve",
            "Freikugel",
            "Reserve",
            "Reserve",
            "Reserve",
            "Reserve",
            "Last Resort",
            "Foul Havoc",
            "Reserve",
            "Earthquake",
            "0x09C",
            "0x09D",
            "Holy Melody",
            "Evil Melody",
            "Spiral Viper",
            "Magma Axis",
            "0x0A2",
            "Gaea Rage",
            "Counter",
            "Retaliate",
            "Avenge",
            "Extra Hit",
            "Tentacle",
            "Attack",
            "Attack",
            "Attack",
            "Attack",
            "Attack",
            "Attack",
            "Attack",
            "Fire Breath",
            "Hellfire",
            "Prominence",
            "Ragnarok",
            "Ice Breath",
            "Glacial Blast",
            "Shock",
            "Bold Storm",
            "Wing Buffet",
            "Tornado",
            "Wind Cutter",
            "Wet Wind",
            "Thunderclap",
            "Holy Wrath",
            "Deathtouch",
            "Mana Drain",
            "Life Drain",
            "Violet Flash",
            "Starlight",
            "Radiance",
            "Hell Gaze",
            "Stone Gaze",
            "Mute Gaze",
            "Evil Gaze",
            "Reserve",
            "Bael's Bane",
            "Toxic Cloud",
            "War Cry",
            "Fog Breath",
            "Taunt",
            "Debilitate",
            "Dismal Tune",
            "Sol Niger",
            "Stun Gaze",
            "Lullaby",
            "Binding Cry",
            "Eternal Rest",
            "Sonic Wave",
            "Sexy Gaze",
            "Allure",
            "Panic Voice",
            "Intoxicate",
            "Prayer",
            "Beast Eye",
            "Dragon Eye",
            "Infinite Light",
            "Summon",
            "Beckon Call",
            "Focus",
            "Retreat",
            "Gathering",
            "Dark Howl",
            "Reserve",
            "Laughter",
            "Divine Will",
            "Reserve",
            "Foul Union",
            "Replicate",
            "Aurora",
            "Fire of Sinai",
            "Conjuration",
            "Reserve",
            "Reserve",
            "Reserve",
            "Reserve",
            "Vast Light",
            "God's Curse",
            "Hell's Call",
            "Icy Death",
            "Mirage",
            "Reserve",
            "Lost Macca!",
            "Reserve",
            "Wild Dance",
            "Domination",
            "Samrecarm",
            "Gathering",
            "Apocalypse",
            "Phase Shift",
            "(Summon)",
            "Attack",
            "Fire of Sinai",
            "Attack",
            "Death Flies",
            "Death Flies",
            "Soul Divide",
            "E & I/Boogie Woogie",
            "Rebellion/Enter Yoshitsune",
            "Bullet-Time/Mokoi Boomerang",
            "Provoke",
            "Stinger/Tekisatsu",
            "Roundtrip/Mishaguji Raiden",
            "Whirlwind/Hitokoto Storm",
            "Showtime/Jiraiya Dance",
            "Attack",
            "Evil Gleam",
            "Root of Evil",
            "High King",
            "Holy Star/Raptor Guardian",
            "Andalucia",
            "Red Capote",
            "Startle",
            "Preach",
            "Meditation",
            "Terrorblade",
            "Hell Spin",
            "Hell Exhaust",
            "Hell Burner",
            "Hell Throttle",
            "Death Lust",
            "Beast Roar",
            "God's Bow",
            "Reserve",
            "Reserve",
            "Life Bonus",
            "Life Gain",
            "Life Surge",
            "Mana Bonus",
            "Mana Gain",
            "Mana Surge",
            "Fast Retreat",
            "Reserve",
            "Mind's Eye",
            "Might",
            "Bright Might",
            "Dark Might",
            "Drain Attack",
            "Reserve",
            "Attack All",
            "Counter",
            "Retaliate",
            "Avange",
            "Reserve",
            "Fire Boost",
            "Ice Boost",
            "Elec Boost",
            "Force Boost",
            "Anti-Phys",
            "Anti-Fire",
            "Anti-Ice",
            "Anti-Elec",
            "Anti-Force",
            "Anti-Expel",
            "Anti-Death",
            "Anti-Curse",
            "Anti-Nerve",
            "Anti-Mind",
            "Void Phys",
            "Void Fire",
            "Void Ice",
            "Void Elec",
            "Void Force",
            "Void Expel",
            "Void Death",
            "Void Curse",
            "Void Nerve",
            "Void Mind",
            "Phys Drain",
            "Fire Drain",
            "Ice Drain",
            "Elec Drain",
            "Force Drain",
            "Phys Repel",
            "Fire Repel",
            "Ice Repel",
            "Elec Repel",
            "Force Repel",
            "Reserve",
            "Reserve",
            "Endure",
            "Life Aid",
            "Mana Aid",
            "Victory Cry",
            "Life Refill",
            "Mana Refill",
            "Thief's Lore",
            "Reserve",
            "Lucky Find",
            "Watchful",
            "Charisma",
            "Reserve",
            "Pierce",
            "0x166",
            "0x167",
            "Never Yield/Endure",
            "Son's Oath/Raidou the Eternal",
            "0x16A",
            "0x16B",
            "0x16AC",
            "0x16D",
            "0x16E",
            "0x16F",
            "0x170",
            "0x171",
            "0x172",
            "0x173",
            "0x174",
            "0x175",
            "0x176",
            "0x177",
            "0x178",
            "0x179",
            "0x17A",
            "0x17B",
            "0x17C",
            "0x17D",
            "0x17E",
            "0x17F",
            "Talk",
            "Scout",
            "Kidnap",
            "Seduce",
            "Brainwash",
            "Reserve",
            "Dark Pledge",
            "Wooing",
            "Beseech",
            "Soul Recruit",
            "Mischief",
            "Death Pact",
            "Pester",
            "Begging",
            "Threaten",
            "Stone Hunt",
            "Trade",
            "Loan",
            "Reserve",
            "Reserve",
            "Reserve",
            "Reserve",
            "Reserve",
            "Reserve",
            "Reserve",
            "Haggle",
            "Arbitration",
            "Detain",
            "Gonnection",
            "Persuade",
            "Intimidate",
            "Nag",
            "Reserve",
            "Reserve",
            "Maiden Plea",
            "Wine Party",
            "Flatter",
            "Jive Talk",
            "0x1A6",
            "0x1A7",
            "0x1A8",
            "0x1A9",
            "0x1AA",
            "0x1AB",
            "0x1AC",
            "0x1AD",
            "0x1AE",
            "0x1AF",
            "0x1B0",
            "0x1B1",
            "0x1B2",
            "0x1B3",
            "0x1B4",
            "0x1B5",
            "0x1B6",
            "0x1B7",
            "0x1B8",
            "0x1B9",
            "0x1BA",
            "0x1BB",
            "0x1BC",
            "0x1BD",
            "0x1BE",
            "0x1BF",
            "0x1C0",
            "0x1C1",
            "0x1C2",
            "0x1C3",
            "0x1C4",
            "0x1C5",
            "0x1C6",
            "0x1C7",
            "0x1C8",
            "0x1C9",
            "0x1CA",
            "0x1CB",
            "0x1CC",
            "0x1CD",
            "0x1CE",
            "0x1CF",
            "0x1D0",
            "0x1D1",
            "0x1D2",
            "0x1D3",
            "0x1D4",
            "0x1D5",
            "0x1D6",
            "0x1D7",
            "0x1D8",
            "0x1D9",
            "0x1DA",
            "0x1DB",
            "0x1DC",
            "0x1DD",
            "0x1DE",
            "0x1DF",
            "0x1E0",
            "0x1E1",
            "0x1E2",
            "0x1E3",
            "0x1E4",
            "0x1E5",
            "0x1E6",
            "0x1E7",
            "0x1E8",
            "0x1E9",
            "0x1EA",
            "0x1EB",
            "0x1EC",
            "0x1ED",
            "0x1EE",
            "0x1EF",
            "Call Angel",
            "Call Soldier",
            "Call Souls",
            "Call Evil",
            "0x1F4",
            "0x1F5",
            "0x1F6",
            "0x1F7",
            "0x1F8",
            "0x1F9",
            "0x1FA",
            "0x1FB",
            "0x1FC",
            "0x1FD",
            "0x1FE",
            "0x1FF"
        };

    }
}
